#!/usr/bin/env bash
export AE_WORKSPACE_PATH=/home/v-xli2/AugmentedAutoencoder/ws2/

python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_01.ply' --obj_id 1
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_02.ply' --obj_id 2
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_03.ply' --obj_id 3
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_04.ply' --obj_id 4
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_05.ply' --obj_id 5
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_06.ply' --obj_id 6
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_07.ply' --obj_id 7
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_08.ply' --obj_id 8
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_09.ply' --obj_id 9
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_10.ply' --obj_id 10
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_11.ply' --obj_id 11
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_12.ply' --obj_id 12
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_13.ply' --obj_id 13
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_14.ply' --obj_id 14
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_15.ply' --obj_id 15
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_16.ply' --obj_id 16
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_17.ply' --obj_id 17
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_18.ply' --obj_id 18
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_19.ply' --obj_id 19
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_20.ply' --obj_id 20
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_21.ply' --obj_id 21
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_22.ply' --obj_id 22
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_23.ply' --obj_id 23
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_24.ply' --obj_id 24
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_25.ply' --obj_id 25
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_26.ply' --obj_id 26
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_27.ply' --obj_id 27
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_28.ply' --obj_id 28
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_29.ply' --obj_id 29
python auto_pose/eval/ae_eval.py exp_group/my_mpencoder gtbboxmulti --eval_cfg eval_template.cfg --model_path '/home/v-xli2/AugmentedAutoencoder/dataset/t-less/t-less/models_cad_subdivided/obj_30.ply' --obj_id 30